# Generated by Django 3.2 on 2023-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='colaborators',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile'),
        ),
    ]
