# Generated by Django 3.2 on 2023-04-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspace_colaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleworkspace',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
            preserve_default=False,
        ),
    ]
