# Generated by Django 3.2 on 2023-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_styleworkspace_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleworkspace',
            name='bg_color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='styleworkspace',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='workspaces/background'),
        ),
    ]
