# Generated by Django 3.2 on 2023-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
        ('workspaces', '0007_auto_20230404_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='asigned',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
