# Generated by Django 3.2 on 2023-04-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_alter_workspace_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkspace',
            name='style',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='style',
        ),
    ]
