# Generated by Django 3.2 on 2023-04-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_auto_20230404_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='style',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.styleworkspace'),
        ),
    ]
