# Generated by Django 3.2 on 2023-04-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_alter_workspace_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='style',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='workspaces.styleworkspace'),
            preserve_default=False,
        ),
    ]
