# Generated by Django 3.2 on 2023-04-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_auto_20230404_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleworkspace',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='workspaces.workspace'),
        ),
    ]
