# Generated by Django 3.2 on 2023-04-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_alter_todo_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='workspaces.workspace'),
        ),
    ]
