# Generated by Django 3.2 on 2023-04-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0020_alter_todo_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltodo',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
